--liquibase formatted sql
--changeset Daniel Aguilar:1.0.0
CREATE TABLE game (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT game_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  game_id INTEGER NOT NULL,
  account_name VARCHAR(25) NOT NULL,
  balance INTEGER NOT NULL,
  pin CHAR(4) NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_key UNIQUE (game_id, account_name),
  CONSTRAINT account_game_fkey
    FOREIGN KEY (game_id) REFERENCES game (id)
);

ALTER TABLE game ADD COLUMN bank_id INTEGER;
ALTER TABLE game ADD COLUMN banker_id INTEGER;
ALTER TABLE game ADD CONSTRAINT game_bank_fkey
  FOREIGN KEY (bank_id) REFERENCES account (id);
ALTER TABLE game ADD CONSTRAINT game_banker_fkey
  FOREIGN KEY (banker_id) REFERENCES account (id);


CREATE TABLE exchange ( -- aka transaction (reserved word)
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  sender_id INTEGER NOT NULL,
  recipient_id INTEGER NOT NULL,
  amount INTEGER NOT NULL,
  exchange_date TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT exchange_pkey PRIMARY KEY (id),
  CONSTRAINT exchange_sender_fkey
    FOREIGN KEY (sender_id) REFERENCES account (id),
  CONSTRAINT exchange_recipient_fkey
    FOREIGN KEY (recipient_id) REFERENCES account (id)
);

--changeset Daniel Aguilar:1574640900 context:test
INSERT INTO game (id) VALUES (1);
INSERT INTO game (id) VALUES (2);

INSERT INTO account (id, game_id, account_name, balance, pin)
  VALUES (1, 1, 'Bank', 1000, '0000');
INSERT INTO account (id, game_id, account_name, balance, pin)
  VALUES (2, 1, 'Banker', 100, '1234');
INSERT INTO account (id, game_id, account_name, balance, pin)
  VALUES (3, 1, 'Player', 100, '4321');

UPDATE game SET bank_id = 1, banker_id = 2 WHERE id = 1;

ALTER TABLE game ALTER COLUMN id RESTART WITH 3;
ALTER TABLE account ALTER COLUMN id RESTART WITH 4;
