name: Supabase Activity Scheduler
on:
  schedule:
    - cron: "0 0 * * WED,SUN"
jobs:
  send-http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl https://cashless-375154748704.us-central1.run.app/sb/wake-up
